apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.user | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.password | quote }}
