apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-frontend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: sausage-frontend
    app.kubernetes.io/component: frontend
    env: "{{ .Values.environment }}" 
{{- include "labels" . | indent 4 }}
spec:
  revisionHistoryLimit: 12 # Keeps 12 old ReplicaSets for potential rollbacks (default: 10)
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
      # # The scheduler will prefer nodes labeled app=frontend for this pod. If such a node is available, it’s very likely (weight=80/100) to be chosen, but the pod may still land on another node if needed.
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 80
      #       preference:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - frontend
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
