image:
  repository: selnastol/sausage-frontend
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  host: sausage-store.local
