apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  REPORT_PATH: "/var/www-data/htdocs"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/sausage_db"
  SPRING_DATA_MONGODB_URI: "mongodb://sausage_user:sausage_password@mongodb:27017/sausage_reports?authSource=admin"
