apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "{{ .Values.postgres.user | default "sausage_user" }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgres.password | default "sausage_password" }}"
