apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.password | quote }}
  POSTGRES_DB: {{ .Values.db | quote }}
