apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-report-config
  namespace: default
data:
  PORT: "8080"
  DB: "mongodb://sausage_user:sausage_password@mongodb:27017/sausage_reports?authSource=admin"
