apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  namespace: default
  labels:
    app: backend-report
spec:
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: backend-report
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
      - name: backend-report
        image: selnastol/sausage-backend-report:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        envFrom:
        - configMapRef:
            name: backend-report-config
        ports:
        - containerPort: 8080
          name: backend-report
